//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS.
//

import Foundation

class ___VARIABLE_sceneName___Configurator {
    
    static func inject(dependencyFor viewController: ___VARIABLE_sceneName___UI) {
        let router = ___VARIABLE_sceneName___Router()
        let presenter = ___VARIABLE_sceneName___Presenter()
    
        let interactor = ___VARIABLE_sceneName___Interactor(get___VARIABLE_sceneName___Usecase: BaseUsecase<Void, Void>)
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        
        presenter.viewController = viewController
        
        router.viewController = viewController
    }
}
