//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

struct ___VARIABLE_sceneName___Model: Codable{
    
    var id: Int?
    var name: String?
    var description: String?
    
    enum CodingKeys: String, CodingKey{
        case id = "id"
        case name = "name"
        case description = "description"
    }

}
