//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation
import ObjectMapper

class ___VARIABLE_sceneName___Model: ___VARIABLE_sceneName___Entity, Mappable {
    
    init() {
        super.init()
    }
    
    required init?(map: Map) {
        super.init()
        self.id = 0
        self.name = ""
        self.description = ""
    }

    func mapping(map: Map) {
        id <- map["property_id"]
        name <- map["name"]
        description <- map["description"]
    }
}
