//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

class ___VARIABLE_sceneName___RepositoryImpl: ___VARIABLE_sceneName___RepositoryLogic {
    
    private let datasource: ___VARIABLE_sceneName___RemoteDataSource
    
    init(datasource: ___VARIABLE_sceneName___RemoteDataSource) {
        self.datasource = datasource
    }
    
    func get___VARIABLE_sceneName___(parameter: [String : Any],
                                     completion: @escaping (Result<[___VARIABLE_sceneName___Entity], DataError>) -> Void) {
        
        datasource.fetch___VARIABLE_sceneName___(param: parameter) { result in
            switch result {
            case .failure(let error):
                completion(.failure(error))
            case .success(let models):
                let entities = models
                    .map { model -> ___VARIABLE_sceneName___Entity in
                        return ___VARIABLE_sceneName___Entity(id: model.id, name: model.name, description: model.name)
                    }
                completion(.success(entities))
            }
        }
    }
}
