//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

class ___VARIABLE_sceneName___Entity: BaseEntity {
    
    var id: Int
    var name: String
    var description: String
    
    init(id: Int = 0, name: String = "", description: String = "") {
        self.id = id
        self.name = name
        self.description = description
    }
    
    
}
