//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation

protocol ___VARIABLE_sceneName___RepositoryLogic {
    func get___VARIABLE_sceneName___(parameter: [String: Any],
                             completion: @escaping(Result<[___VARIABLE_sceneName___Entity], DataError>) -> Void)
}

